// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package database

import (
	"context"
	"database/sql"
)

const deleteClientById = `-- name: DeleteClientById :exec
DELETE FROM clients
WHERE
    id = ?
`

func (q *Queries) DeleteClientById(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClientById, id)
	return err
}

const getAllClients = `-- name: GetAllClients :many
SELECT
    id, client_name, client_phone, import_export, import_fee, export_fee, after_hours_charges, pet_name, species, gender, breed, date_of_birth, microchip_number, titre, last_rabies_date, rabies_validity, documentation_status, rabies_vaccination_valid, other_vaccines_completed, health_certificate_issues, export_permit_approved, import_permit_approved, airline_approval_received, customs_clearance_done, origin_country, destination_country, forwarder_charges, departure, airline, airline_charges, crate_cost, flight_number, type_of_travel, etd, eta, quoted_amount, total_cost, profit, advanced_received, balance_pending, payment_status, remarks, created_at, updated_at
FROM
    clients
`

func (q *Queries) GetAllClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, getAllClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientName,
			&i.ClientPhone,
			&i.ImportExport,
			&i.ImportFee,
			&i.ExportFee,
			&i.AfterHoursCharges,
			&i.PetName,
			&i.Species,
			&i.Gender,
			&i.Breed,
			&i.DateOfBirth,
			&i.MicrochipNumber,
			&i.Titre,
			&i.LastRabiesDate,
			&i.RabiesValidity,
			&i.DocumentationStatus,
			&i.RabiesVaccinationValid,
			&i.OtherVaccinesCompleted,
			&i.HealthCertificateIssues,
			&i.ExportPermitApproved,
			&i.ImportPermitApproved,
			&i.AirlineApprovalReceived,
			&i.CustomsClearanceDone,
			&i.OriginCountry,
			&i.DestinationCountry,
			&i.ForwarderCharges,
			&i.Departure,
			&i.Airline,
			&i.AirlineCharges,
			&i.CrateCost,
			&i.FlightNumber,
			&i.TypeOfTravel,
			&i.Etd,
			&i.Eta,
			&i.QuotedAmount,
			&i.TotalCost,
			&i.Profit,
			&i.AdvancedReceived,
			&i.BalancePending,
			&i.PaymentStatus,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientById = `-- name: GetClientById :one
SELECT
    id, client_name, client_phone, import_export, import_fee, export_fee, after_hours_charges, pet_name, species, gender, breed, date_of_birth, microchip_number, titre, last_rabies_date, rabies_validity, documentation_status, rabies_vaccination_valid, other_vaccines_completed, health_certificate_issues, export_permit_approved, import_permit_approved, airline_approval_received, customs_clearance_done, origin_country, destination_country, forwarder_charges, departure, airline, airline_charges, crate_cost, flight_number, type_of_travel, etd, eta, quoted_amount, total_cost, profit, advanced_received, balance_pending, payment_status, remarks, created_at, updated_at
FROM
    clients
WHERE
    id = ?
`

func (q *Queries) GetClientById(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientById, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.ClientPhone,
		&i.ImportExport,
		&i.ImportFee,
		&i.ExportFee,
		&i.AfterHoursCharges,
		&i.PetName,
		&i.Species,
		&i.Gender,
		&i.Breed,
		&i.DateOfBirth,
		&i.MicrochipNumber,
		&i.Titre,
		&i.LastRabiesDate,
		&i.RabiesValidity,
		&i.DocumentationStatus,
		&i.RabiesVaccinationValid,
		&i.OtherVaccinesCompleted,
		&i.HealthCertificateIssues,
		&i.ExportPermitApproved,
		&i.ImportPermitApproved,
		&i.AirlineApprovalReceived,
		&i.CustomsClearanceDone,
		&i.OriginCountry,
		&i.DestinationCountry,
		&i.ForwarderCharges,
		&i.Departure,
		&i.Airline,
		&i.AirlineCharges,
		&i.CrateCost,
		&i.FlightNumber,
		&i.TypeOfTravel,
		&i.Etd,
		&i.Eta,
		&i.QuotedAmount,
		&i.TotalCost,
		&i.Profit,
		&i.AdvancedReceived,
		&i.BalancePending,
		&i.PaymentStatus,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByName = `-- name: GetClientByName :many
SELECT
    id, client_name, client_phone, import_export, import_fee, export_fee, after_hours_charges, pet_name, species, gender, breed, date_of_birth, microchip_number, titre, last_rabies_date, rabies_validity, documentation_status, rabies_vaccination_valid, other_vaccines_completed, health_certificate_issues, export_permit_approved, import_permit_approved, airline_approval_received, customs_clearance_done, origin_country, destination_country, forwarder_charges, departure, airline, airline_charges, crate_cost, flight_number, type_of_travel, etd, eta, quoted_amount, total_cost, profit, advanced_received, balance_pending, payment_status, remarks, created_at, updated_at
FROM
    clients
WHERE
    client_name = ?
`

func (q *Queries) GetClientByName(ctx context.Context, clientName sql.NullString) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, getClientByName, clientName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientName,
			&i.ClientPhone,
			&i.ImportExport,
			&i.ImportFee,
			&i.ExportFee,
			&i.AfterHoursCharges,
			&i.PetName,
			&i.Species,
			&i.Gender,
			&i.Breed,
			&i.DateOfBirth,
			&i.MicrochipNumber,
			&i.Titre,
			&i.LastRabiesDate,
			&i.RabiesValidity,
			&i.DocumentationStatus,
			&i.RabiesVaccinationValid,
			&i.OtherVaccinesCompleted,
			&i.HealthCertificateIssues,
			&i.ExportPermitApproved,
			&i.ImportPermitApproved,
			&i.AirlineApprovalReceived,
			&i.CustomsClearanceDone,
			&i.OriginCountry,
			&i.DestinationCountry,
			&i.ForwarderCharges,
			&i.Departure,
			&i.Airline,
			&i.AirlineCharges,
			&i.CrateCost,
			&i.FlightNumber,
			&i.TypeOfTravel,
			&i.Etd,
			&i.Eta,
			&i.QuotedAmount,
			&i.TotalCost,
			&i.Profit,
			&i.AdvancedReceived,
			&i.BalancePending,
			&i.PaymentStatus,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertClient = `-- name: InsertClient :one
INSERT INTO
    clients (
        id,
        client_name,
        client_phone,
        import_export,
        import_fee,
        export_fee,
        after_hours_charges,
        pet_name,
        species,
        gender,
        breed,
        date_of_birth,
        microchip_number,
        titre,
        last_rabies_date,
        rabies_validity,
        documentation_status,
        rabies_vaccination_valid,
        other_vaccines_completed,
        health_certificate_issues,
        export_permit_approved,
        import_permit_approved,
        airline_approval_received,
        customs_clearance_done,
        origin_country,
        destination_country,
        forwarder_charges,
        departure,
        airline,
        airline_charges,
        crate_cost,
        flight_number,
        type_of_travel,
        etd,
        eta,
        quoted_amount,
        total_cost,
        profit,
        advanced_received,
        balance_pending,
        payment_status,
        remarks
    )
VALUES
    (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    ) RETURNING id, client_name, client_phone, import_export, import_fee, export_fee, after_hours_charges, pet_name, species, gender, breed, date_of_birth, microchip_number, titre, last_rabies_date, rabies_validity, documentation_status, rabies_vaccination_valid, other_vaccines_completed, health_certificate_issues, export_permit_approved, import_permit_approved, airline_approval_received, customs_clearance_done, origin_country, destination_country, forwarder_charges, departure, airline, airline_charges, crate_cost, flight_number, type_of_travel, etd, eta, quoted_amount, total_cost, profit, advanced_received, balance_pending, payment_status, remarks, created_at, updated_at
`

type InsertClientParams struct {
	ID                      string          `json:"id"`
	ClientName              sql.NullString  `json:"client_name"`
	ClientPhone             sql.NullString  `json:"client_phone"`
	ImportExport            sql.NullString  `json:"import_export"`
	ImportFee               sql.NullFloat64 `json:"import_fee"`
	ExportFee               sql.NullFloat64 `json:"export_fee"`
	AfterHoursCharges       sql.NullFloat64 `json:"after_hours_charges"`
	PetName                 sql.NullString  `json:"pet_name"`
	Species                 sql.NullString  `json:"species"`
	Gender                  sql.NullString  `json:"gender"`
	Breed                   sql.NullString  `json:"breed"`
	DateOfBirth             sql.NullTime    `json:"date_of_birth"`
	MicrochipNumber         sql.NullString  `json:"microchip_number"`
	Titre                   sql.NullTime    `json:"titre"`
	LastRabiesDate          sql.NullTime    `json:"last_rabies_date"`
	RabiesValidity          sql.NullTime    `json:"rabies_validity"`
	DocumentationStatus     sql.NullInt64   `json:"documentation_status"`
	RabiesVaccinationValid  sql.NullInt64   `json:"rabies_vaccination_valid"`
	OtherVaccinesCompleted  sql.NullString  `json:"other_vaccines_completed"`
	HealthCertificateIssues sql.NullInt64   `json:"health_certificate_issues"`
	ExportPermitApproved    sql.NullInt64   `json:"export_permit_approved"`
	ImportPermitApproved    sql.NullInt64   `json:"import_permit_approved"`
	AirlineApprovalReceived sql.NullInt64   `json:"airline_approval_received"`
	CustomsClearanceDone    sql.NullInt64   `json:"customs_clearance_done"`
	OriginCountry           sql.NullString  `json:"origin_country"`
	DestinationCountry      sql.NullString  `json:"destination_country"`
	ForwarderCharges        sql.NullFloat64 `json:"forwarder_charges"`
	Departure               sql.NullTime    `json:"departure"`
	Airline                 sql.NullString  `json:"airline"`
	AirlineCharges          sql.NullFloat64 `json:"airline_charges"`
	CrateCost               sql.NullFloat64 `json:"crate_cost"`
	FlightNumber            sql.NullString  `json:"flight_number"`
	TypeOfTravel            sql.NullString  `json:"type_of_travel"`
	Etd                     interface{}     `json:"etd"`
	Eta                     interface{}     `json:"eta"`
	QuotedAmount            sql.NullFloat64 `json:"quoted_amount"`
	TotalCost               sql.NullFloat64 `json:"total_cost"`
	Profit                  sql.NullFloat64 `json:"profit"`
	AdvancedReceived        sql.NullFloat64 `json:"advanced_received"`
	BalancePending          sql.NullFloat64 `json:"balance_pending"`
	PaymentStatus           sql.NullString  `json:"payment_status"`
	Remarks                 sql.NullString  `json:"remarks"`
}

func (q *Queries) InsertClient(ctx context.Context, arg InsertClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, insertClient,
		arg.ID,
		arg.ClientName,
		arg.ClientPhone,
		arg.ImportExport,
		arg.ImportFee,
		arg.ExportFee,
		arg.AfterHoursCharges,
		arg.PetName,
		arg.Species,
		arg.Gender,
		arg.Breed,
		arg.DateOfBirth,
		arg.MicrochipNumber,
		arg.Titre,
		arg.LastRabiesDate,
		arg.RabiesValidity,
		arg.DocumentationStatus,
		arg.RabiesVaccinationValid,
		arg.OtherVaccinesCompleted,
		arg.HealthCertificateIssues,
		arg.ExportPermitApproved,
		arg.ImportPermitApproved,
		arg.AirlineApprovalReceived,
		arg.CustomsClearanceDone,
		arg.OriginCountry,
		arg.DestinationCountry,
		arg.ForwarderCharges,
		arg.Departure,
		arg.Airline,
		arg.AirlineCharges,
		arg.CrateCost,
		arg.FlightNumber,
		arg.TypeOfTravel,
		arg.Etd,
		arg.Eta,
		arg.QuotedAmount,
		arg.TotalCost,
		arg.Profit,
		arg.AdvancedReceived,
		arg.BalancePending,
		arg.PaymentStatus,
		arg.Remarks,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.ClientPhone,
		&i.ImportExport,
		&i.ImportFee,
		&i.ExportFee,
		&i.AfterHoursCharges,
		&i.PetName,
		&i.Species,
		&i.Gender,
		&i.Breed,
		&i.DateOfBirth,
		&i.MicrochipNumber,
		&i.Titre,
		&i.LastRabiesDate,
		&i.RabiesValidity,
		&i.DocumentationStatus,
		&i.RabiesVaccinationValid,
		&i.OtherVaccinesCompleted,
		&i.HealthCertificateIssues,
		&i.ExportPermitApproved,
		&i.ImportPermitApproved,
		&i.AirlineApprovalReceived,
		&i.CustomsClearanceDone,
		&i.OriginCountry,
		&i.DestinationCountry,
		&i.ForwarderCharges,
		&i.Departure,
		&i.Airline,
		&i.AirlineCharges,
		&i.CrateCost,
		&i.FlightNumber,
		&i.TypeOfTravel,
		&i.Etd,
		&i.Eta,
		&i.QuotedAmount,
		&i.TotalCost,
		&i.Profit,
		&i.AdvancedReceived,
		&i.BalancePending,
		&i.PaymentStatus,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClientById = `-- name: UpdateClientById :one
UPDATE clients
SET
    client_name = ?,
    client_phone = ?,
    import_export = ?,
    import_fee = ?,
    export_fee = ?,
    after_hours_charges = ?,
    pet_name = ?,
    species = ?,
    gender = ?,
    breed = ?,
    date_of_birth = ?,
    microchip_number = ?,
    titre = ?,
    last_rabies_date = ?,
    rabies_validity = ?,
    documentation_status = ?,
    rabies_vaccination_valid = ?,
    other_vaccines_completed = ?,
    health_certificate_issues = ?,
    export_permit_approved = ?,
    import_permit_approved = ?,
    airline_approval_received = ?,
    customs_clearance_done = ?,
    origin_country = ?,
    destination_country = ?,
    forwarder_charges = ?,
    departure = ?,
    airline = ?,
    airline_charges = ?,
    crate_cost = ?,
    flight_number = ?,
    type_of_travel = ?,
    etd = ?,
    eta = ?,
    quoted_amount = ?,
    total_cost = ?,
    profit = ?,
    advanced_received = ?,
    balance_pending = ?,
    payment_status = ?,
    remarks = ?
WHERE
    id = ? RETURNING id, client_name, client_phone, import_export, import_fee, export_fee, after_hours_charges, pet_name, species, gender, breed, date_of_birth, microchip_number, titre, last_rabies_date, rabies_validity, documentation_status, rabies_vaccination_valid, other_vaccines_completed, health_certificate_issues, export_permit_approved, import_permit_approved, airline_approval_received, customs_clearance_done, origin_country, destination_country, forwarder_charges, departure, airline, airline_charges, crate_cost, flight_number, type_of_travel, etd, eta, quoted_amount, total_cost, profit, advanced_received, balance_pending, payment_status, remarks, created_at, updated_at
`

type UpdateClientByIdParams struct {
	ClientName              sql.NullString  `json:"client_name"`
	ClientPhone             sql.NullString  `json:"client_phone"`
	ImportExport            sql.NullString  `json:"import_export"`
	ImportFee               sql.NullFloat64 `json:"import_fee"`
	ExportFee               sql.NullFloat64 `json:"export_fee"`
	AfterHoursCharges       sql.NullFloat64 `json:"after_hours_charges"`
	PetName                 sql.NullString  `json:"pet_name"`
	Species                 sql.NullString  `json:"species"`
	Gender                  sql.NullString  `json:"gender"`
	Breed                   sql.NullString  `json:"breed"`
	DateOfBirth             sql.NullTime    `json:"date_of_birth"`
	MicrochipNumber         sql.NullString  `json:"microchip_number"`
	Titre                   sql.NullTime    `json:"titre"`
	LastRabiesDate          sql.NullTime    `json:"last_rabies_date"`
	RabiesValidity          sql.NullTime    `json:"rabies_validity"`
	DocumentationStatus     sql.NullInt64   `json:"documentation_status"`
	RabiesVaccinationValid  sql.NullInt64   `json:"rabies_vaccination_valid"`
	OtherVaccinesCompleted  sql.NullString  `json:"other_vaccines_completed"`
	HealthCertificateIssues sql.NullInt64   `json:"health_certificate_issues"`
	ExportPermitApproved    sql.NullInt64   `json:"export_permit_approved"`
	ImportPermitApproved    sql.NullInt64   `json:"import_permit_approved"`
	AirlineApprovalReceived sql.NullInt64   `json:"airline_approval_received"`
	CustomsClearanceDone    sql.NullInt64   `json:"customs_clearance_done"`
	OriginCountry           sql.NullString  `json:"origin_country"`
	DestinationCountry      sql.NullString  `json:"destination_country"`
	ForwarderCharges        sql.NullFloat64 `json:"forwarder_charges"`
	Departure               sql.NullTime    `json:"departure"`
	Airline                 sql.NullString  `json:"airline"`
	AirlineCharges          sql.NullFloat64 `json:"airline_charges"`
	CrateCost               sql.NullFloat64 `json:"crate_cost"`
	FlightNumber            sql.NullString  `json:"flight_number"`
	TypeOfTravel            sql.NullString  `json:"type_of_travel"`
	Etd                     interface{}     `json:"etd"`
	Eta                     interface{}     `json:"eta"`
	QuotedAmount            sql.NullFloat64 `json:"quoted_amount"`
	TotalCost               sql.NullFloat64 `json:"total_cost"`
	Profit                  sql.NullFloat64 `json:"profit"`
	AdvancedReceived        sql.NullFloat64 `json:"advanced_received"`
	BalancePending          sql.NullFloat64 `json:"balance_pending"`
	PaymentStatus           sql.NullString  `json:"payment_status"`
	Remarks                 sql.NullString  `json:"remarks"`
	ID                      string          `json:"id"`
}

func (q *Queries) UpdateClientById(ctx context.Context, arg UpdateClientByIdParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClientById,
		arg.ClientName,
		arg.ClientPhone,
		arg.ImportExport,
		arg.ImportFee,
		arg.ExportFee,
		arg.AfterHoursCharges,
		arg.PetName,
		arg.Species,
		arg.Gender,
		arg.Breed,
		arg.DateOfBirth,
		arg.MicrochipNumber,
		arg.Titre,
		arg.LastRabiesDate,
		arg.RabiesValidity,
		arg.DocumentationStatus,
		arg.RabiesVaccinationValid,
		arg.OtherVaccinesCompleted,
		arg.HealthCertificateIssues,
		arg.ExportPermitApproved,
		arg.ImportPermitApproved,
		arg.AirlineApprovalReceived,
		arg.CustomsClearanceDone,
		arg.OriginCountry,
		arg.DestinationCountry,
		arg.ForwarderCharges,
		arg.Departure,
		arg.Airline,
		arg.AirlineCharges,
		arg.CrateCost,
		arg.FlightNumber,
		arg.TypeOfTravel,
		arg.Etd,
		arg.Eta,
		arg.QuotedAmount,
		arg.TotalCost,
		arg.Profit,
		arg.AdvancedReceived,
		arg.BalancePending,
		arg.PaymentStatus,
		arg.Remarks,
		arg.ID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.ClientPhone,
		&i.ImportExport,
		&i.ImportFee,
		&i.ExportFee,
		&i.AfterHoursCharges,
		&i.PetName,
		&i.Species,
		&i.Gender,
		&i.Breed,
		&i.DateOfBirth,
		&i.MicrochipNumber,
		&i.Titre,
		&i.LastRabiesDate,
		&i.RabiesValidity,
		&i.DocumentationStatus,
		&i.RabiesVaccinationValid,
		&i.OtherVaccinesCompleted,
		&i.HealthCertificateIssues,
		&i.ExportPermitApproved,
		&i.ImportPermitApproved,
		&i.AirlineApprovalReceived,
		&i.CustomsClearanceDone,
		&i.OriginCountry,
		&i.DestinationCountry,
		&i.ForwarderCharges,
		&i.Departure,
		&i.Airline,
		&i.AirlineCharges,
		&i.CrateCost,
		&i.FlightNumber,
		&i.TypeOfTravel,
		&i.Etd,
		&i.Eta,
		&i.QuotedAmount,
		&i.TotalCost,
		&i.Profit,
		&i.AdvancedReceived,
		&i.BalancePending,
		&i.PaymentStatus,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
