// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Client struct {
	ID                      string          `json:"id"`
	ClientName              sql.NullString  `json:"client_name"`
	ClientPhone             sql.NullString  `json:"client_phone"`
	ImportExport            sql.NullString  `json:"import_export"`
	ImportFee               sql.NullFloat64 `json:"import_fee"`
	ExportFee               sql.NullFloat64 `json:"export_fee"`
	AfterHoursCharges       sql.NullFloat64 `json:"after_hours_charges"`
	PetName                 sql.NullString  `json:"pet_name"`
	Species                 sql.NullString  `json:"species"`
	Gender                  sql.NullString  `json:"gender"`
	Breed                   sql.NullString  `json:"breed"`
	DateOfBirth             sql.NullTime    `json:"date_of_birth"`
	MicrochipNumber         sql.NullString  `json:"microchip_number"`
	Titre                   sql.NullTime    `json:"titre"`
	LastRabiesDate          sql.NullTime    `json:"last_rabies_date"`
	RabiesValidity          sql.NullTime    `json:"rabies_validity"`
	DocumentationStatus     sql.NullInt64   `json:"documentation_status"`
	RabiesVaccinationValid  sql.NullInt64   `json:"rabies_vaccination_valid"`
	OtherVaccinesCompleted  sql.NullString  `json:"other_vaccines_completed"`
	HealthCertificateIssues sql.NullInt64   `json:"health_certificate_issues"`
	ExportPermitApproved    sql.NullInt64   `json:"export_permit_approved"`
	ImportPermitApproved    sql.NullInt64   `json:"import_permit_approved"`
	AirlineApprovalReceived sql.NullInt64   `json:"airline_approval_received"`
	CustomsClearanceDone    sql.NullInt64   `json:"customs_clearance_done"`
	OriginCountry           sql.NullString  `json:"origin_country"`
	DestinationCountry      sql.NullString  `json:"destination_country"`
	ForwarderCharges        sql.NullFloat64 `json:"forwarder_charges"`
	Departure               sql.NullTime    `json:"departure"`
	Airline                 sql.NullString  `json:"airline"`
	AirlineCharges          sql.NullFloat64 `json:"airline_charges"`
	CrateCost               sql.NullFloat64 `json:"crate_cost"`
	FlightNumber            sql.NullString  `json:"flight_number"`
	TypeOfTravel            sql.NullString  `json:"type_of_travel"`
	Etd                     interface{}     `json:"etd"`
	Eta                     interface{}     `json:"eta"`
	QuotedAmount            sql.NullFloat64 `json:"quoted_amount"`
	TotalCost               sql.NullFloat64 `json:"total_cost"`
	Profit                  sql.NullFloat64 `json:"profit"`
	AdvancedReceived        sql.NullFloat64 `json:"advanced_received"`
	BalancePending          sql.NullFloat64 `json:"balance_pending"`
	PaymentStatus           sql.NullString  `json:"payment_status"`
	Remarks                 sql.NullString  `json:"remarks"`
	CreatedAt               sql.NullTime    `json:"created_at"`
	UpdatedAt               sql.NullTime    `json:"updated_at"`
	MicrochipValidity       sql.NullTime    `json:"microchip_validity"`
	NotificationMicrochip   int64           `json:"notification_microchip"`
	NotificationRabies      int64           `json:"notification_rabies"`
}

type User struct {
	ID           string       `json:"id"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
