// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const getUserByName = `-- name: GetUserByName :one
SELECT
    id, username, password_hash, created_at, updated_at
FROM
    users
WHERE
    username = ?
`

func (q *Queries) GetUserByName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserByName = `-- name: InsertUserByName :one
INSERT INTO
    users (id, username, password_hash)
VALUES
    (?, ?, ?) RETURNING id, username, password_hash, created_at, updated_at
`

type InsertUserByNameParams struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) InsertUserByName(ctx context.Context, arg InsertUserByNameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUserByName, arg.ID, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserByName = `-- name: UpdateUserByName :one
UPDATE users
SET
    id = ?,
    username = ?,
    password_hash = ? RETURNING id, username, password_hash, created_at, updated_at
`

type UpdateUserByNameParams struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserByName(ctx context.Context, arg UpdateUserByNameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserByName, arg.ID, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
